# -*- coding: utf-8 -*-
{
    'name': 'Template Report Module',
    'version': '1.0',
    'summary': 'Basic structure for QWeb report in Odoo',
    'category': 'Reporting',
    'author': 'YHA',
    'depends': ['base', 'sale','purchase','report_xlsx','product'],
    'data': [
        'reports/sale_a5_voucher_template.xml',
        'reports/report_action.xml',
        'reports/sales_customize_template.xml',
        'reports/sales_order_with_photo_template.xml',
        'reports/purchase_order_customize_report_template.xml',
        'reports/purchase_quotation_customize_report_template.xml',
        'reports/purchase_order_with_photo_template.xml',
        'reports/sale_and_loading_list_template.xml',
        'reports/address_print_template.xml',
        'reports/pan_sar_template.xml',
        'reports/transfer_report_template.xml',
        'reports/delivery_return_report_template.xml',
        'reports/draft_voucher_report.xml',
    ],
    'installable': True,
    'application': False,
}